name: Pull request checks

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.TOKEN_NPM}}" >> ~/.npmrc
      - run: echo "@verybigthings:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - run: npm i
      - run: npx lerna bootstrap --no-ci
      - run: npm run lint
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.TOKEN_NPM}}" >> ~/.npmrc
      - run: echo "@verybigthings:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - run: npm i
      - run: npx lerna bootstrap --no-ci
      - run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.TOKEN_NPM}}" >> ~/.npmrc
      - run: echo "@verybigthings:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - run: npm i
      - run: npx lerna bootstrap --no-ci
      - run: npm run build
